# This is a basic workflow to help you get started with Actions

name: Continous Deployment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    tags:
      - '*'

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.0
    
      - name: Run analysis and tests
        uses: highbyte/sonarscan-dotnet@1.0
        with:
          sonarHostName: https://sonarqube.mihben.net
          sonarProjectKey: netension_monitoring
          sonarProjectName: .Netension.Monitoring
          dotnetBuildArguments: ./src/*.sln --configuration Release
          dotnetTestArguments: ./src/*.sln --logger trx --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
          sonarBeginArguments: /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml" -d:sonar.cs.vstest.reportsPaths="**/TestResults/*.trx"
  publish:
    runs-on: ubuntu-latest
    needs: [build]
    if: success()
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Create NuGet packages
        run: dotnet pack ./src/*.sln --configuration Release --output ./artifacts/
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2.1.4
        with:
          path: ./artifacts/*.nupkg
